### ISSUE TITLE
Релизы

### ISSUE THREAD

**Issue by NEO-SPECTRUMAN** [vpyk/emu80v4#12]
А почему нет релизов пристегнутых к самому гитхабу?
ГЯФ и emu80.org в укрожопии забанены
конечно скачать от туда можно но...
сюда тоже цепляется драгндропом

**Comment by vpyk** [comment]
Принято, сделал релиз, пока только последней версии.

**Comment by NEO-SPECTRUMAN** [comment]
да в принципе токо посследня и нада
а через проксю я один скачал
а второй (Emu80qt_40400.zip) качаю досих пор :rofl:
