### ISSUE TITLE
PVS Studio analysis

### ISSUE THREAD

**Issue by nzeemin** [vpyk/emu80v4#15]
Замечания, найденные с помощью PVS Studio:

1. CrtRenderer.cpp:144
Не освобождается массив `rowLengths` - memory leak.

2. Pk8000.cpp:262
`m_blanking` всегда равно `true`, тернарный оператор не нужен, можно заменить на `BS_BLANK`:
```
            m_blankingPixels[(i + m_pixelsPerOutInstruction) % 320] = m_blanking ? BS_BLANK : BS_NORMAL;
```

3. `V547 Expression '* ptr != 0xD0' is always false. Pk8000.cpp 806`
Тут непонятно зачем нужен этот `if`, код под ним никогда не будет исполняться. Но тогда и `for` не нужен. В общем, тут явно что-то очень не так.
```
    if (*ptr == 0xD0) {
        // Binary file
        for (int i = 0; i < 10; i++)
            if (*ptr != 0xD0) {
                delete[] buf;
                return false;
            }
```
4. `V547 Expression '* ptr != 0xD3' is always false. Pk8000.cpp 891`
Аналогично предыдущему.
```
    } else if (*ptr == 0xD3) {
        // Basic file
        for (int i = 0; i < 10; i++)
            if (*ptr != 0xD3) {
                delete[] buf;
                return false;
            }
```

5. `V519 The 'm_portC' variable is assigned values twice successively. Perhaps this is a mistake. Check lines: 42, 43. Ppi8255.cpp 43`
`m_portC` обнуляется дважды.

6. `V688 The 'm_presetMenu' local variable possesses the same name as one of the class members, which can result in a confusion. qtMainWindow.cpp 1161`
Здесь `m_presetMenu` это локальная переменная с тем же именем что и член класса - получается, что член класса не будет заполнен.
```
    QMenu* m_presetMenu = new QMenu (tr("Window size"), this);
```

7. `V773 Visibility scope of the 'dialog' pointer was exited without releasing the memory. A memory leak is possible. qtMainWindow.cpp 2532`
Экземпляр `AboutDialog` создаётся и не освобождается - memory leak.

8. `V517 The use of 'if (A) {...} else if (A) {...}' pattern was detected. There is a probability of logical error presence. Check lines: 2978, 2981. qtMainWindow.cpp 2978`
Похоже, в последнем `if` должно быть "5x":
```
        } else if (frameScale == "4x") {
            m_preset4xAction->setChecked(true);
            m_presetAction->setIcon(m_4xIcon);
        } else if (frameScale == "4x") {
            m_preset5xAction->setChecked(true);
            m_presetAction->setIcon(m_5xIcon);
```

9. `V523 The 'then' statement is equivalent to the 'else' statement. SdAdapters.cpp 68`
Обе ветки под условием одинаковы.
```
    if (m_type != SDA_MSX)
        addr == 0 ? writeDataPort(value) :  writeConfPort(value);
    else
        addr == 0 ? writeDataPort(value) :  writeConfPort(value);
```

10. `V547 Expression 'firstLine == lastLine' is always false. Vector.cpp 370`
Тернарный оператор не нужен, можно его заменить на 0.
```
    if (firstLine != lastLine)
        renderLine(lastLine, firstLine == lastLine ? firstPixel : 0, lastPixel);
```

**Comment by nzeemin** [comment]
Прикладываю полный отчёт в виде HTML:
[fullhtml.zip](https://github.com/vpyk/emu80v4/files/9915506/fullhtml.zip)

**Comment by vpyk** [comment]
@nzeemin, спасибо, весьма полезная информация. Буду анализировать.
Кроме очевидных багов попадаются и нетривиальные вещи, тот же п.3:
`V547 Expression '* ptr != 0xD0' is always false`
никак не соответствует действительности, очень даже бывает true и работает как задумано. Надо вникать, что-то действительно там очень не так...

**Comment by vpyk** [comment]
Отчет проанализирован, внесены необходимые изменения.
