### ISSUE TITLE
Issues detected using PVS-Studio 

### ISSUE THREAD

**Issue by nzeemin** [vpyk/emu80v4#5]
1. qtSettingsDialog.cpp:641 -- строка совпадает со строкой 636, думаю тут должно быть color2RadioButton
```
        } else if (ui->color1RadioButton->isChecked()) {
            if (m_platformGroup == "rk86")
                val = "color2";
            else if (m_platformGroup == "spec")
                val = "8color";
        }
```

2.1. Micro80.cpp:69 -- объём выделяемой памяти отличается от объёма очищаемой.
```
    m_bufSize = m_prevBufSize = m_sizeX * m_sizeY;
    m_pixelData = new uint32_t[512 * 512];
    m_prevPixelData = new uint32_t[512 * 512];
    memset(m_pixelData, 0, m_bufSize * sizeof(uint32_t));
    memset(m_prevPixelData, 0, m_prevBufSize * sizeof(uint32_t));
```
2.2. Ut88.cpp:65 -- то же самое

3. Debugger.cpp:1695 -- `~1` даёт отрицательное число типа int, лучше привести его к uint16_t перед сдвигом:
```
           af &= ~1 << bitNo;
```

4.1. CpuZ80.cpp:1952 -- используются макросы BC, DE, HL, которые раскрываются в regs[regs_sel].bc итд., в результате тут имеем 6 присваиваний из регистра в него же, вместо обмена. Также советую прогнать программные тесты Z80 чтобы проверить эту ошибку и выявить другие.
```
    case 0xD9:          /* EXX */
        regs[regs_sel].bc = BC;
        regs[regs_sel].de = DE;
        regs[regs_sel].hl = HL;
        regs_sel = 1 - regs_sel;
        BC = regs[regs_sel].bc;
        DE = regs[regs_sel].de;
        HL = regs[regs_sel].hl;
        break;
```
4.2. CpuZ80.cpp:840 -- та же ситуация:
```
    case 0x08:          /* EX AF,AF' */
        af[af_sel] = AF;
        af_sel = 1 - af_sel;
        AF = af[af_sel];
        break;
```
5. CpuZ80.cpp:281 -- очень странная работа с битами, через двойное логическое отрицание:
```
            cbshflg1:
                AF = (AF & ~0xff) | (temp & 0xa8) |
                    (((temp & 0xff) == 0) << 6) |
                    parity(temp) | !!cbits;
```

**Comment by vpyk** [comment]
1, 2 - fixed
3-5 - буду смотреть

**Comment by vpyk** [comment]
3 - fixed
На самом деле там еще и скобок не хватало:
            af &= ~((uint16_t)1 << bitNo);

4,5 - можешь посоветовать какие-нибудь тесты для Z80?
К тому же код не мой, нужно время разобраться...

**Comment by nzeemin** [comment]
@vpyk, по тестам для z80 видимо вот это: http://mdfs.net/Software/Z80/Exerciser/

**Comment by vpyk** [comment]
Вспомнил про незакрытый issue...

4 - fixed, ошибка вкралась в процессе адаптации чужого кода, запустил тест, может быть и еще что-нибудь всплывет.
5 - можно, конечно, поменять на "cbits ? 1 : 0", я в подобных случаях именно так и пишу. но есть ли смысл? Вроде бы !!x довольно часто используется? Не думаю, что какой-то компилятор будет трактовать это особым образом...

**Comment by vpyk** [comment]
Тест zexall пройден успешно, но он, видимо, не исчерпывающий...
